/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

/// AccessKeyOperation : Access key operation

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccessKeyOperation {
    /// Name of the operation
    #[serde(rename = "operation", skip_serializing_if = "Option::is_none")]
    pub operation: Option<String>,
    /// Tags associated with the operation
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl AccessKeyOperation {
    /// Access key operation
    pub fn new() -> AccessKeyOperation {
        AccessKeyOperation {
            operation: None,
            tags: None,
        }
    }
}
