/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AttachInstanceToPrivateNetworkRequest {
    /// Static IP address lease for the corresponding network interface
    #[serde(rename = "ip", skip_serializing_if = "Option::is_none")]
    pub ip: Option<String>,
    #[serde(rename = "instance")]
    pub instance: Box<crate::models::Instance>,
}

impl AttachInstanceToPrivateNetworkRequest {
    pub fn new(instance: crate::models::Instance) -> AttachInstanceToPrivateNetworkRequest {
        AttachInstanceToPrivateNetworkRequest {
            ip: None,
            instance: Box::new(instance),
        }
    }
}
