/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

/// CdnConfiguration : CDN configuration

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CdnConfiguration {
    /// CDN configuration bucket name
    #[serde(rename = "bucket", skip_serializing_if = "Option::is_none")]
    pub bucket: Option<String>,
    /// CDN configuration status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// FQDN that serves the bucket contents
    #[serde(rename = "fqdn", skip_serializing_if = "Option::is_none")]
    pub fqdn: Option<String>,
}

impl CdnConfiguration {
    /// CDN configuration
    pub fn new() -> CdnConfiguration {
        CdnConfiguration {
            bucket: None,
            status: None,
            fqdn: None,
        }
    }
}

/// CDN configuration status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "deactivated")]
    Deactivated,
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "activated")]
    Activated,
}

impl Default for Status {
    fn default() -> Status {
        Self::Deactivated
    }
}
