/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateInstancePoolRequest {
    /// Instance Pool Anti-affinity Groups
    #[serde(
        rename = "anti-affinity-groups",
        skip_serializing_if = "Option::is_none"
    )]
    pub anti_affinity_groups: Option<Vec<crate::models::AntiAffinityGroup>>,
    /// Instance Pool description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "public-ip-assignment",
        skip_serializing_if = "Option::is_none"
    )]
    pub public_ip_assignment: Option<crate::models::PublicIpAssignment>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<::std::collections::HashMap<String, String>>,
    /// Instance Pool Security Groups
    #[serde(rename = "security-groups", skip_serializing_if = "Option::is_none")]
    pub security_groups: Option<Vec<crate::models::SecurityGroup>>,
    /// Instances Elastic IPs
    #[serde(rename = "elastic-ips", skip_serializing_if = "Option::is_none")]
    pub elastic_ips: Option<Vec<crate::models::ElasticIp>>,
    /// Instance Pool name
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "instance-type")]
    pub instance_type: Box<crate::models::InstanceType>,
    /// Minimum number of running Instances
    #[serde(rename = "min-available", skip_serializing_if = "Option::is_none")]
    pub min_available: Option<i64>,
    /// Instance Pool Private Networks
    #[serde(rename = "private-networks", skip_serializing_if = "Option::is_none")]
    pub private_networks: Option<Vec<crate::models::PrivateNetwork>>,
    #[serde(rename = "template")]
    pub template: Box<crate::models::Template>,
    /// Number of Instances
    #[serde(rename = "size")]
    pub size: i64,
    #[serde(rename = "ssh-key", skip_serializing_if = "Option::is_none")]
    pub ssh_key: Option<Box<crate::models::SshKey>>,
    /// Prefix to apply to Instances names (default: pool)
    #[serde(rename = "instance-prefix", skip_serializing_if = "Option::is_none")]
    pub instance_prefix: Option<String>,
    /// Instances Cloud-init user-data
    #[serde(rename = "user-data", skip_serializing_if = "Option::is_none")]
    pub user_data: Option<String>,
    #[serde(rename = "deploy-target", skip_serializing_if = "Option::is_none")]
    pub deploy_target: Option<Box<crate::models::DeployTarget>>,
    /// Enable IPv6. DEPRECATED: use `public-ip-assignments`.
    #[serde(rename = "ipv6-enabled", skip_serializing_if = "Option::is_none")]
    pub ipv6_enabled: Option<bool>,
    /// Instances disk size in GB
    #[serde(rename = "disk-size")]
    pub disk_size: i64,
}

impl CreateInstancePoolRequest {
    pub fn new(
        name: String,
        instance_type: crate::models::InstanceType,
        template: crate::models::Template,
        size: i64,
        disk_size: i64,
    ) -> CreateInstancePoolRequest {
        CreateInstancePoolRequest {
            anti_affinity_groups: None,
            description: None,
            public_ip_assignment: None,
            labels: None,
            security_groups: None,
            elastic_ips: None,
            name,
            instance_type: Box::new(instance_type),
            min_available: None,
            private_networks: None,
            template: Box::new(template),
            size,
            ssh_key: None,
            instance_prefix: None,
            user_data: None,
            deploy_target: None,
            ipv6_enabled: None,
            disk_size,
        }
    }
}
