/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateDbaasServiceMysqlRequestIntegrationsInner {
    #[serde(rename = "type")]
    pub _type: crate::models::EnumIntegrationTypes,
    #[serde(rename = "source-service", skip_serializing_if = "Option::is_none")]
    pub source_service: Option<String>,
    #[serde(rename = "dest-service", skip_serializing_if = "Option::is_none")]
    pub dest_service: Option<String>,
    /// Integration settings
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<serde_json::Value>,
}

impl CreateDbaasServiceMysqlRequestIntegrationsInner {
    pub fn new(
        _type: crate::models::EnumIntegrationTypes,
    ) -> CreateDbaasServiceMysqlRequestIntegrationsInner {
        CreateDbaasServiceMysqlRequestIntegrationsInner {
            _type,
            source_service: None,
            dest_service: None,
            settings: None,
        }
    }
}
