/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

/// DbaasPlan : DBaaS plan

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DbaasPlan {
    /// DBaaS plan name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// DBaaS plan node count
    #[serde(rename = "node-count", skip_serializing_if = "Option::is_none")]
    pub node_count: Option<i64>,
    /// DBaaS plan CPU count per node
    #[serde(rename = "node-cpu-count", skip_serializing_if = "Option::is_none")]
    pub node_cpu_count: Option<i64>,
    /// DBaaS plan disk space
    #[serde(rename = "disk-space", skip_serializing_if = "Option::is_none")]
    pub disk_space: Option<i64>,
    /// DBaaS plan memory count per node
    #[serde(rename = "node-memory", skip_serializing_if = "Option::is_none")]
    pub node_memory: Option<i64>,
    /// DBaaS plan max memory allocated percentage
    #[serde(rename = "max-memory-percent", skip_serializing_if = "Option::is_none")]
    pub max_memory_percent: Option<i64>,
    #[serde(rename = "backup-config", skip_serializing_if = "Option::is_none")]
    pub backup_config: Option<Box<crate::models::DbaasBackupConfig>>,
    /// Requires authorization or publicly available
    #[serde(rename = "authorized", skip_serializing_if = "Option::is_none")]
    pub authorized: Option<bool>,
}

impl DbaasPlan {
    /// DBaaS plan
    pub fn new() -> DbaasPlan {
        DbaasPlan {
            name: None,
            node_count: None,
            node_cpu_count: None,
            disk_space: None,
            node_memory: None,
            max_memory_percent: None,
            backup_config: None,
            authorized: None,
        }
    }
}
