/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

/// DbaasServiceNotification : Service notifications

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DbaasServiceNotification {
    /// Notification level
    #[serde(rename = "level")]
    pub level: Level,
    /// Human notification message
    #[serde(rename = "message")]
    pub message: String,
    /// Notification type
    #[serde(rename = "type")]
    pub _type: Type,
    /// Notification type
    #[serde(rename = "metadata")]
    pub metadata: serde_json::Value,
}

impl DbaasServiceNotification {
    /// Service notifications
    pub fn new(
        level: Level,
        message: String,
        _type: Type,
        metadata: serde_json::Value,
    ) -> DbaasServiceNotification {
        DbaasServiceNotification {
            level,
            message,
            _type,
            metadata,
        }
    }
}

/// Notification level
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Level {
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "notice")]
    Notice,
}

impl Default for Level {
    fn default() -> Level {
        Self::Warning
    }
}
/// Notification type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "service_powered_off_removal")]
    PoweredOffRemoval,
    #[serde(rename = "service_end_of_life")]
    EndOfLife,
}

impl Default for Type {
    fn default() -> Type {
        Self::PoweredOffRemoval
    }
}
