/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DbaasIntegration {
    /// Description of the integration
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Integration settings
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<serde_json::Value>,
    /// Integration type
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    /// Whether the integration is enabled or not
    #[serde(rename = "is-enabled", skip_serializing_if = "Option::is_none")]
    pub is_enabled: Option<bool>,
    /// Source service name
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// Whether the integration is active or not
    #[serde(rename = "is-active", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<bool>,
    /// Integration status
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Integration id
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Destination service name
    #[serde(rename = "dest", skip_serializing_if = "Option::is_none")]
    pub dest: Option<String>,
}

impl DbaasIntegration {
    pub fn new() -> DbaasIntegration {
        DbaasIntegration {
            description: None,
            settings: None,
            _type: None,
            is_enabled: None,
            source: None,
            is_active: None,
            status: None,
            id: None,
            dest: None,
        }
    }
}
