/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

/// DnsDomain : DNS domain

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DnsDomain {
    /// DNS domain ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// DNS domain creation date
    #[serde(rename = "created-at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// DNS domain unicode name
    #[serde(rename = "unicode-name", skip_serializing_if = "Option::is_none")]
    pub unicode_name: Option<String>,
}

impl DnsDomain {
    /// DNS domain
    pub fn new() -> DnsDomain {
        DnsDomain {
            id: None,
            created_at: None,
            unicode_name: None,
        }
    }
}
