/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EnumComponentUsage {
    #[serde(rename = "primary")]
    Primary,
    #[serde(rename = "replica")]
    Replica,
}

impl ToString for EnumComponentUsage {
    fn to_string(&self) -> String {
        match self {
            Self::Primary => String::from("primary"),
            Self::Replica => String::from("replica"),
        }
    }
}

impl Default for EnumComponentUsage {
    fn default() -> EnumComponentUsage {
        Self::Primary
    }
}
