/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EnumIntegrationTypes {
    #[serde(rename = "datasource")]
    Datasource,
    #[serde(rename = "read_replica")]
    ReadReplica,
    #[serde(rename = "metrics")]
    Metrics,
}

impl ToString for EnumIntegrationTypes {
    fn to_string(&self) -> String {
        match self {
            Self::Datasource => String::from("datasource"),
            Self::ReadReplica => String::from("read_replica"),
            Self::Metrics => String::from("metrics"),
        }
    }
}

impl Default for EnumIntegrationTypes {
    fn default() -> EnumIntegrationTypes {
        Self::Datasource
    }
}
