/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetDbaasSettingsPg200ResponseSettings {
    #[serde(rename = "pg", skip_serializing_if = "Option::is_none")]
    pub pg: Option<Box<crate::models::GetDbaasSettingsPg200ResponseSettingsPg>>,
    #[serde(rename = "pglookout", skip_serializing_if = "Option::is_none")]
    pub pglookout: Option<Box<crate::models::GetDbaasSettingsPg200ResponseSettingsPglookout>>,
    #[serde(rename = "pgbouncer", skip_serializing_if = "Option::is_none")]
    pub pgbouncer: Option<Box<crate::models::GetDbaasSettingsPg200ResponseSettingsPgbouncer>>,
    #[serde(rename = "timescaledb", skip_serializing_if = "Option::is_none")]
    pub timescaledb: Option<Box<crate::models::GetDbaasSettingsPg200ResponseSettingsTimescaledb>>,
}

impl GetDbaasSettingsPg200ResponseSettings {
    pub fn new() -> GetDbaasSettingsPg200ResponseSettings {
        GetDbaasSettingsPg200ResponseSettings {
            pg: None,
            pglookout: None,
            pgbouncer: None,
            timescaledb: None,
        }
    }
}
