/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

/// InstancePool : Instance Pool

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InstancePool {
    /// Instance Pool Anti-affinity Groups
    #[serde(
        rename = "anti-affinity-groups",
        skip_serializing_if = "Option::is_none"
    )]
    pub anti_affinity_groups: Option<Vec<crate::models::AntiAffinityGroup>>,
    /// Instance Pool description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(
        rename = "public-ip-assignment",
        skip_serializing_if = "Option::is_none"
    )]
    pub public_ip_assignment: Option<crate::models::PublicIpAssignment>,
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<::std::collections::HashMap<String, String>>,
    /// Instance Pool Security Groups
    #[serde(rename = "security-groups", skip_serializing_if = "Option::is_none")]
    pub security_groups: Option<Vec<crate::models::SecurityGroup>>,
    /// Instances Elastic IPs
    #[serde(rename = "elastic-ips", skip_serializing_if = "Option::is_none")]
    pub elastic_ips: Option<Vec<crate::models::ElasticIp>>,
    /// Instance Pool name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "instance-type", skip_serializing_if = "Option::is_none")]
    pub instance_type: Option<Box<crate::models::InstanceType>>,
    /// Minimum number of running instances
    #[serde(rename = "min-available", skip_serializing_if = "Option::is_none")]
    pub min_available: Option<i64>,
    /// Instance Pool Private Networks
    #[serde(rename = "private-networks", skip_serializing_if = "Option::is_none")]
    pub private_networks: Option<Vec<crate::models::PrivateNetwork>>,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<Box<crate::models::Template>>,
    /// Instance Pool state
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,
    /// Number of instances
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
    #[serde(rename = "ssh-key", skip_serializing_if = "Option::is_none")]
    pub ssh_key: Option<Box<crate::models::SshKey>>,
    /// The instances created by the Instance Pool will be prefixed with this value (default: pool)
    #[serde(rename = "instance-prefix", skip_serializing_if = "Option::is_none")]
    pub instance_prefix: Option<String>,
    /// Instances Cloud-init user-data
    #[serde(rename = "user-data", skip_serializing_if = "Option::is_none")]
    pub user_data: Option<String>,
    #[serde(rename = "manager", skip_serializing_if = "Option::is_none")]
    pub manager: Option<Box<crate::models::Manager>>,
    /// Instances
    #[serde(rename = "instances", skip_serializing_if = "Option::is_none")]
    pub instances: Option<Vec<crate::models::Instance>>,
    #[serde(rename = "deploy-target", skip_serializing_if = "Option::is_none")]
    pub deploy_target: Option<Box<crate::models::DeployTarget>>,
    /// Enable IPv6 for instances
    #[serde(rename = "ipv6-enabled", skip_serializing_if = "Option::is_none")]
    pub ipv6_enabled: Option<bool>,
    /// Instance Pool ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Instances disk size in GB
    #[serde(rename = "disk-size", skip_serializing_if = "Option::is_none")]
    pub disk_size: Option<i64>,
}

impl InstancePool {
    /// Instance Pool
    pub fn new() -> InstancePool {
        InstancePool {
            anti_affinity_groups: None,
            description: None,
            public_ip_assignment: None,
            labels: None,
            security_groups: None,
            elastic_ips: None,
            name: None,
            instance_type: None,
            min_available: None,
            private_networks: None,
            template: None,
            state: None,
            size: None,
            ssh_key: None,
            instance_prefix: None,
            user_data: None,
            manager: None,
            instances: None,
            deploy_target: None,
            ipv6_enabled: None,
            id: None,
            disk_size: None,
        }
    }
}

/// Instance Pool state
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "scaling-up")]
    ScalingUp,
    #[serde(rename = "scaling-down")]
    ScalingDown,
    #[serde(rename = "destroying")]
    Destroying,
    #[serde(rename = "creating")]
    Creating,
    #[serde(rename = "suspended")]
    Suspended,
    #[serde(rename = "running")]
    Running,
}

impl Default for State {
    fn default() -> State {
        Self::ScalingUp
    }
}
