/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListAccessKeys200Response {
    #[serde(rename = "access-keys", skip_serializing_if = "Option::is_none")]
    pub access_keys: Option<Vec<crate::models::AccessKey>>,
}

impl ListAccessKeys200Response {
    pub fn new() -> ListAccessKeys200Response {
        ListAccessKeys200Response { access_keys: None }
    }
}
