/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListDbaasIntegrationTypes200Response {
    #[serde(
        rename = "dbaas-integration-types",
        skip_serializing_if = "Option::is_none"
    )]
    pub dbaas_integration_types: Option<Vec<crate::models::DbaasIntegrationType>>,
}

impl ListDbaasIntegrationTypes200Response {
    pub fn new() -> ListDbaasIntegrationTypes200Response {
        ListDbaasIntegrationTypes200Response {
            dbaas_integration_types: None,
        }
    }
}
