/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

/// OperationReference : Related resource reference

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OperationReference {
    /// Reference ID
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Link to the referenced resource
    #[serde(rename = "link", skip_serializing_if = "Option::is_none")]
    pub link: Option<String>,
    /// Command name
    #[serde(rename = "command", skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
}

impl OperationReference {
    /// Related resource reference
    pub fn new() -> OperationReference {
        OperationReference {
            id: None,
            link: None,
            command: None,
        }
    }
}
