/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PromoteSnapshotToTemplateRequest {
    /// Template name
    #[serde(rename = "name")]
    pub name: String,
    /// Template description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Template default user
    #[serde(rename = "default-user", skip_serializing_if = "Option::is_none")]
    pub default_user: Option<String>,
    /// Enable SSH key-based login in the template
    #[serde(rename = "ssh-key-enabled", skip_serializing_if = "Option::is_none")]
    pub ssh_key_enabled: Option<bool>,
    /// Enable password-based login in the template
    #[serde(rename = "password-enabled", skip_serializing_if = "Option::is_none")]
    pub password_enabled: Option<bool>,
}

impl PromoteSnapshotToTemplateRequest {
    pub fn new(name: String) -> PromoteSnapshotToTemplateRequest {
        PromoteSnapshotToTemplateRequest {
            name,
            description: None,
            default_user: None,
            ssh_key_enabled: None,
            password_enabled: None,
        }
    }
}
