/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PublicIpAssignment {
    #[serde(rename = "inet4")]
    Inet4,
    #[serde(rename = "dual")]
    Dual,
}

impl ToString for PublicIpAssignment {
    fn to_string(&self) -> String {
        match self {
            Self::Inet4 => String::from("inet4"),
            Self::Dual => String::from("dual"),
        }
    }
}

impl Default for PublicIpAssignment {
    fn default() -> PublicIpAssignment {
        Self::Inet4
    }
}
