/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

/// SnapshotExport : Exported snapshot information

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SnapshotExport {
    /// Exported snapshot disk file pre-signed URL
    #[serde(rename = "presigned-url", skip_serializing_if = "Option::is_none")]
    pub presigned_url: Option<String>,
    /// Exported snapshot disk file MD5 checksum
    #[serde(rename = "md5sum", skip_serializing_if = "Option::is_none")]
    pub md5sum: Option<String>,
}

impl SnapshotExport {
    /// Exported snapshot information
    pub fn new() -> SnapshotExport {
        SnapshotExport {
            presigned_url: None,
            md5sum: None,
        }
    }
}
