/*
 * Exoscale Public API
 *
 *  Infrastructure automation API, allowing programmatic access to all Exoscale products and services.  The [OpenAPI Specification](http://spec.openapis.org/oas/v3.0.3.html) source of this documentation can be obtained here:  * [JSON format](https://bump.sh/doc/exoscale-api.json) * [YAML format](https://bump.sh/doc/exoscale-api.yaml)
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: api@exoscale.com
 * Generated by: https://openapi-generator.tech
 */

/// UpdateDbaasServiceKafkaRequestAuthenticationMethods : Kafka authentication methods

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateDbaasServiceKafkaRequestAuthenticationMethods {
    /// Enable certificate/SSL authentication
    #[serde(rename = "certificate", skip_serializing_if = "Option::is_none")]
    pub certificate: Option<bool>,
    /// Enable SASL authentication
    #[serde(rename = "sasl", skip_serializing_if = "Option::is_none")]
    pub sasl: Option<bool>,
}

impl UpdateDbaasServiceKafkaRequestAuthenticationMethods {
    /// Kafka authentication methods
    pub fn new() -> UpdateDbaasServiceKafkaRequestAuthenticationMethods {
        UpdateDbaasServiceKafkaRequestAuthenticationMethods {
            certificate: None,
            sasl: None,
        }
    }
}
