name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.0.0

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unit tests
        run: cargo test --verbose
        env:
          EXOSCALE_API_KEY: ${{ secrets.EXOSCALE_API_KEY }}
          EXOSCALE_SECRET: ${{ secrets.EXOSCALE_SECRET }}
          EXOSCALE_TEMPLATE: ${{ secrets.EXOSCALE_TEMPLATE }}


  cargo-deny:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources

    continue-on-error: ${{ matrix.checks == 'advisories' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run cargo deny
        uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check ${{ matrix.checks }}
